export const breeds = [
  'Abyssinian',
  'Aegean',
  'American Bobtail',
  'Asian Semi-longhair',
  'Bengal',
  'Birman	',
  'British Shorthair',
  'Cyprus',
  'Donskoy',
  'Egyptian Mau',
  'Foldex',
  'Havana Brown',
  'Khao Manee',
  'Korat',
  'Persian',
  'Scottish Fold',
  'Sphynx',
  'York Chocolate',
];
